import mongoose from 'mongoose';

export const PASS_TYPES = ['General', 'VIP', 'Donor', 'Volunteer', 'Staff', 'Media'];
export const PASS_STATUSES = ['unused', 'used', 'revoked'];

const passSchema = new mongoose.Schema(
  {
    token: { type: String, required: true, unique: true },
    donor_name: { type: String, required: true, trim: true },
    phone: { type: String, trim: true, default: '' },
    email: { type: String, trim: true, default: '' },
    // Pass types come from the selected event's categories on the main system
    // (e.g. Invitee, Sponsor, General Public), so no fixed allow-list.
    pass_type: { type: String, default: 'General' },
    notes: { type: String, trim: true, default: '' },
    qr_content: { type: String, required: true },
    // Where the QR came from: 'main-system' = claimed from the main Prasadam system,
    // 'local' = generated by this app (standalone mode).
    source: { type: String, enum: ['main-system', 'local'], default: 'local' },
    // Main-system references (only set when source === 'main-system').
    recipient_id: { type: String, default: null },
    // Main-system QR id (e.g. ISK-EVT26-GN-0000123) — used for gate matching.
    qr_token: { type: String, default: '' },
    // Main-system QR image (base64 PNG data URL) — shown on the pass card.
    main_qr_image: { type: String, default: '' },
    status: { type: String, enum: PASS_STATUSES, default: 'unused', index: true },
    // WhatsApp delivery tracking: 'pending' (not yet sent), 'sent', 'delivered', 'failed'.
    delivery_status: { type: String, enum: ['pending', 'sent', 'delivered', 'failed'], default: 'pending' },
    event_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Event', default: null, index: true },
    issued_by: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    checked_in_at: { type: Date, default: null },
    valid_from: { type: Date, default: null },
    valid_until: { type: Date, default: null },
  },
  {
    timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' },
  }
);

export default mongoose.models.Pass || mongoose.model('Pass', passSchema);
